# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
# Site settings
title: Marius Mateoc
email: mateoc.marius@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A webdesigner & frontend developer who love to build clean,
  semantic and responsive websites with latest technologies.
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://mariusmateoc.com/ # the base hostname & protocol for your site

# Used so Jekyll outputs the site correctly so Gulp can do what it wants
source: src
destination: dist
exclude: ['assets']

# Same as the title etc for your site but can instead be
# called by using 'site.author.name' and so on
# NOTE: Don't use @ in front of your Twitter username
author:
  name: Marius Mateoc
  email: mateoc.marius@gmail.com
  uri: http://mariusmateoc.com/
  bio: Web Designer &amp; Frontend Developer
  twitter: MariusMateoc
  github: mariusmateoc

# Disable disquss on localhost
enable_disqus: false

# _config.build.yml overwrites these options when you run `gulp build`
# Enables future posts (posts with dates in the future) and drafts
future: true
show_drafts: true
# Disables the more accurate related posts for faster generating of the site
lsi: false
# Only make the last 10 posts so generating isn't slow
limit_posts: 10

# Permalink structure and pagination options
# relative_permalinks: true
permalink: /blog/:title/
paginate: 3
paginate_path: "blog/page:num"
# paginate_path: 'page:num'
excerpt_separator: '<!--more-->'

collections:
  projects:
    output: true
    permalink: /projects/:path/

# Markdown library
markdown: kramdown

highlighter: rouge

# Extending Jekyll
gems:
  - jekyll-archives
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - classifier-reborn
  - algoliasearch-jekyll

algolia:
  application_id: 'SN1KT5NAN0'
  index_name: 'personal_blog'
  read_only_api_key: '4c28ff48cda67f43efac8ae3a3cd69eb'
  attributesToIndex:
    - unordered(title)
    - unordered(text)
  excluded_files:
    - 404.html
    - index.html
    - anthem-vault.markdown
    - locksmith.markdown
    - nest.markdown
    - legal.md
    - about.html
    - contact.html
